spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      order : 2
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    restart:
      enabled: true
  datasource:
    hikari:
      jdbc-url: 'jdbc:log4jdbc:oracle:thin:@192.168.1.252:1522:orcl'
      username: 'happy_dev'
      password: 'dev1023'
      driver-class-name: 'net.sf.log4jdbc.sql.jdbcapi.DriverSpy'
      connection-timeout: 200000
      auto-commit: false
      minimum-idle: 3
      maximum-pool-size: 3
      connection-test-query: SELECT 1 FROM DUAL
mybatis:
  type-aliases-package: com.happymoney.test
  mapper-locations: /META-INF/mapper/*.xml
server:
  error:
    path: '/WEB-INF/views/error'
  compression:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /
    session:
      timeout: 20m
      cookie:
        http-only: true
        secure: true
        same-site: None
  port: 8081
  address: '0.0.0.0'

logging:
  config: classpath:logback-spring.xml